### ISSUE TITLE
🐛 Bug: crash when logging circular object

### ISSUE THREAD

**Issue by bradzacher** [JoshuaKGoldberg/console-fail-test#206]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/console-fail-test/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.

### Expected

```js
const x = { prop: {} };
x.prop = x;
console.log(x);
```

Expected:
library works

### Actual

```
    TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)
```

### Additional Info

Found this when logging out one of @typescript-eslint's ast objects:

```
    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Object'
        |     property 'object' -> object with constructor 'Object'
        --- property 'parent' closes the circle
        at JSON.stringify (<anonymous>)

      at formatComplaintLineArg (../../node_modules/console-fail-test/src/complaining.js:20:17)
          at Array.map (<anonymous>)
      at formatComplaintCall (../../node_modules/console-fail-test/src/complaining.js:17:49)
      at formatComplaintLineWithIndex (../../node_modules/console-fail-test/src/complaining.js:15:92)
          at Array.map (<anonymous>)
      at formatMethodComplaint (../../node_modules/console-fail-test/src/complaining.js:9:10)
          at Array.map (<anonymous>)
      at createComplaint (../../node_modules/console-fail-test/src/complaining.js:24:47)
      at ../../node_modules/console-fail-test/src/cft.js:36:59
      at afterEachCallback (../../node_modules/console-fail-test/src/environments/jest.js:22:39)
      at Object.<anonymous> (../../node_modules/console-fail-test/src/environments/jest.js:15:9)
```

**Comment by JoshuaKGoldberg** [comment]
Thanks for the report @bradzacher! Fixed in v0.2.3.
